import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, RefreshCw, Shield, Database, GitBranch, FileText, Users, CheckCircle2, AlertTriangle } from 'lucide-react';
import { request } from '../../api/client';
import { ConfirmDialog } from '../common/ConfirmDialog';
import { ToastMessage } from '../common/Toast';

type RecordData = Record<string, any>;
const sections = [
  ['health', '1 采集健康'], ['rechecks', '2 处置复查'], ['storage', '3 存储管理'], ['traffic', '4 流量账本'],
  ['policies', '5 业务策略'], ['baseline', '6 动态基线'], ['incidents', '7 事件时间线'], ['logs', '8 日志接入'],
  ['upgrades', '9 节点升级'], ['services', '10 服务可用性'], ['backups', '11 备份'], ['users', '12 权限与审计'],
] as const;
type Section = typeof sections[number][0];
const labels: Record<string, string> = { healthy: '正常', idle: '零活动', stale: '采集过期', unavailable: '未采集', partial: '采集不完整', disabled: '未启用', permission_denied: '权限不足', parse_error: '解析失败', missing: '文件缺失', not_configured: '未接入', failed: '失败', warning: '警告', critical: '危险', queued: '排队', dispatched: '已下发', running: '执行中', succeeded: '执行成功', awaiting_report: '等待复查', retrying: '复发重试', recurring: '风险持续', verified: '已验证', unverified: '无法确认', open: '进行中', resolved: '已恢复', pending: '待灰度通过', canary: '灰度中', rollout: '分批发布' };
function Status({ value }: { value: string }) {
  const good = ['healthy', 'idle', 'verified', 'resolved', 'succeeded'].includes(value);
  const bad = ['failed', 'critical', 'recurring', 'permission_denied', 'parse_error'].includes(value);
  const unknown = ['stale', 'unavailable', 'disabled', 'unverified', 'not_configured'].includes(value);
  return <span className={`inline-flex rounded-md border px-2 py-1 text-xs ${good ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : bad ? 'border-rose-500/30 bg-rose-500/10 text-rose-300' : unknown ? 'border-slate-600 bg-slate-800 text-slate-300' : 'border-amber-500/30 bg-amber-500/10 text-amber-200'}`}>{labels[value] || value}</span>;
}
const bytes = (n: number = 0) => n >= 1073741824 ? `${(n / 1073741824).toFixed(2)} GiB` : n >= 1048576 ? `${(n / 1048576).toFixed(1)} MiB` : `${Math.round(n / 1024)} KiB`;
const date = (ts?: number) => ts ? new Date(ts * 1000).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '尚无报告';
const field = 'w-full min-w-0 rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm text-slate-200';
const button = 'min-h-11 rounded-lg border border-sky-500/40 bg-sky-500/10 px-3 py-2 text-sm text-sky-200 hover:bg-sky-500/20 disabled:cursor-not-allowed disabled:opacity-40';
function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="min-w-0 rounded-xl border border-slate-800 bg-slate-900/50 p-4"><h3 className="mb-3 text-sm font-semibold text-slate-200">{title}</h3>{children}</section>;
}
function Empty({ text = '尚无数据。更新 Client 后等待一次采集报告。' }: { text?: string }) { return <p className="py-6 text-sm text-slate-400">{text}</p>; }

export function OperationsView({ onToast, isPaused = false }: { onToast: (type: ToastMessage['type'], message: string) => void; isPaused?: boolean }) {
  const [section, setSection] = useState<Section>('health');
  const [session, setSession] = useState<RecordData>({ role: 'viewer' });
  const [overview, setOverview] = useState<RecordData>({ hosts: [], incidents: [], rechecks: [], actions: [] });
  const [data, setData] = useState<RecordData>({});
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState<RecordData>({ profile: 'general', quota_gib: '', quota_warning: .8, interval_hours: 24, retention: 7, role: 'viewer', kind: 'http' });
  const [preview, setPreview] = useState<RecordData | null>(null);
  const [timeline, setTimeline] = useState<RecordData | null>(null);
  const [historyEntity, setHistoryEntity] = useState('');
  const [historyPeriod, setHistoryPeriod] = useState('day');
  const [historyDays, setHistoryDays] = useState(31);
  const [confirm, setConfirm] = useState<{ title: string; message: string; run: () => Promise<unknown> } | null>(null);
  const sequence = useRef(0);
  const admin = session.role === 'admin';
  const change = (key: string, value: any) => { setForm(f => ({ ...f, [key]: value })); setPreview(null); };
  const load = useCallback(async () => {
    const current = ++sequence.current;
    const me = await request<RecordData>('/api/v1/ops/session');
    const summary = await request<RecordData>('/api/v1/ops/overview');
    let info: RecordData = {};
    const endpoint = section === 'baseline' ? 'traffic' : section === 'users' ? 'users' : section;
    if (['storage', 'traffic', 'baseline', 'policies', 'upgrades', 'services', 'backups', 'users'].includes(section)) {
      if (!['backups', 'users'].includes(section) || me.role === 'admin') {
        const suffix = section === 'traffic' ? `?period=${historyPeriod}&days=${historyDays}&entity=${encodeURIComponent(historyEntity)}` : '';
        info = await request<RecordData>(`/api/v1/ops/${endpoint}${suffix}`);
        if (section === 'users') info.audit = (await request<RecordData>('/api/v1/ops/audit')).items;
        if (section === 'policies') info.entities = (await request<RecordData>('/api/v1/ops/traffic')).items;
      }
    }
    if (current === sequence.current) { setSession(me); setOverview(summary); setData(info); }
  }, [section, historyEntity, historyPeriod, historyDays]);
  useEffect(() => {
    let alive = true;
    setLoading(true); setError(''); setPreview(null); setTimeline(null);
    const refresh = async () => {
      try { await load(); if (alive) setError(''); }
      catch (e) { if (alive) setError(e instanceof Error ? e.message : String(e)); }
      finally { if (alive) setLoading(false); }
    };
    void refresh();
    const timer = setInterval(() => { if (!isPaused && !document.hidden) void refresh(); }, 10000);
    return () => { alive = false; sequence.current++; clearInterval(timer); };
  }, [load, isPaused]);
  const act = async (fn: () => Promise<unknown>, message = '操作已完成') => {
    setBusy(true);
    try { await fn(); onToast('success', message); await load(); }
    catch (e) { onToast('error', e instanceof Error ? e.message : String(e)); }
    finally { setBusy(false); setConfirm(null); }
  };
  const post = (path: string, payload: RecordData = {}) => request<RecordData>(`/api/v1/ops/${path}`, { method: 'POST', body: JSON.stringify(payload) });
  const hostSelect = <label className="block text-xs text-slate-400">目标节点<select className={`${field} mt-1`} value={form.host_id || ''} onChange={e => change('host_id', e.target.value)}><option value="">请选择节点</option>{overview.hosts.map((h: RecordData) => <option key={h.node} value={h.host_id}>{h.host_id}</option>)}</select></label>;
  const items: RecordData[] = data.items || [];
  const selectedEntity = form.entity || '';
  const policyPayload = () => ({ entity: selectedEntity, profile: form.profile, rules: { monthly_quota_bytes: Number(form.quota_gib || 0) * 1073741824, quota_warning: Number(form.quota_warning || .8), silent_until: Number(form.silent_hours || 0) > 0 ? Math.floor(Date.now() / 1000 + Number(form.silent_hours) * 3600) : 0, ...(form.connections ? { connections: Number(form.connections) } : {}), ...(form.rx_mbps ? { rx_bps: Number(form.rx_mbps) * 1e6 / 8 } : {}), ...(form.http_rps ? { http_rps: Number(form.http_rps) } : {}) } });
  return <div className="space-y-5 tabular-nums">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold"><Activity className="h-5 w-5 text-sky-400" />运维中心</h2><p className="mt-1 text-xs text-slate-400">采集 → 判断 → 执行 → 复查 · {session.username || '用户'} / {session.role}</p></div><button className={button} disabled={busy} onClick={() => void act(load, '数据已刷新')}><RefreshCw className="mr-1 inline h-4 w-4" />刷新</button></div>
    <nav aria-label="运维功能" className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-4">{sections.map(([key, label]) => <button key={key} onClick={() => setSection(key)} aria-current={section === key ? 'page' : undefined} className={`min-h-11 rounded-lg border p-2 text-left text-sm ${section === key ? 'border-sky-400 bg-sky-500/15 text-sky-200' : 'border-slate-800 bg-slate-900 text-slate-400 hover:text-slate-100'}`}>{label}</button>)}</nav>
    {error && <p role="alert" className="rounded-lg border border-rose-500/30 bg-rose-500/10 p-3 text-rose-300">{error}</p>}
    {loading ? <p aria-live="polite" className="py-8 text-slate-400">正在读取运维数据…</p> : <>
      {section === 'health' && <div className="grid gap-4 lg:grid-cols-2">{!overview.hosts.length && <Empty />}{overview.hosts.map((h: RecordData) => <Card key={h.node} title={h.host_id}><div className="mb-3 flex flex-wrap items-center gap-2"><Status value={h.status} /><span className="text-xs text-slate-500">{date(h.ts)} · {h.data.architecture || '架构未知'}</span></div>{(h.data.health || []).map((s: RecordData) => <div key={s.source} className="space-y-1 border-t border-slate-800 py-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm">{s.source}</span><Status value={h.stale ? 'stale' : s.status} /></div><p className="text-xs text-slate-400">{Object.entries(s.details || {}).map(([k, v]) => `${k}: ${v}`).join(' · ')}</p><p className="text-xs text-slate-500">{s.guidance}</p></div>)}{!h.data.health && <Empty text="旧版 Client 未上报健康诊断，请先升级；不能据此判定数据为真实 0。" />}</Card>)}</div>}
      {section === 'rechecks' && <div className="space-y-4"><Card title="风险执行后的复查"><p className="mb-4 text-xs text-slate-400">执行成功后等待两次新安全报告。风险复发最多重试两次；未采集、禁用安全或离线不会被标记为验证成功。</p>{!overview.rechecks.length && <Empty text="暂无处置复查记录。新执行的弱认证、恶意进程、面板处置会在这里跟踪。" />}{overview.rechecks.map((r: RecordData) => <div key={r.action_id} className="flex flex-wrap justify-between gap-3 border-t border-slate-800 py-3"><div className="min-w-0 break-words"><p className="text-sm">{r.host_id} / {r.container_name} · #{r.action_id}</p><p className="mt-1 text-xs text-slate-400">{r.alert_type} · 重试 {r.attempts}/2 · 干净采样 {r.clean_samples}/2</p><p className="mt-1 text-xs text-slate-500">{r.message} · {r.result_message}</p></div><Status value={r.status} /></div>)}</Card><Card title="最近动作与失败原因">{overview.actions.map((a: RecordData) => <div key={a.id} className="border-t border-slate-800 py-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm">#{a.id} {a.host_id} / {a.container_name} · {a.action_type}</span><Status value={a.status} /></div><p className="mt-1 break-words text-xs text-slate-500">{a.result_message || '等待 Client 回执'} · {date(a.updated_at)}</p></div>)}</Card></div>}
      {section === 'storage' && <><div className="grid gap-4 sm:grid-cols-3">{[['数据库', data.database_bytes], ['WAL', data.wal_bytes], ['可复用空间', data.reusable_bytes]].map(([label, n]) => <Card key={String(label)} title={String(label)}><p className="font-mono text-xl text-sky-300">{bytes(Number(n))}</p></Card>)}</div><Card title="保留策略与清理状态"><p className="text-sm text-slate-400">原始 {Math.round(data.raw_retention_seconds / 86400)} 天 · 小时汇总 30 天 · 日汇总 400 天。按表统计可能不含共享索引；已清理的页可复用，不会立即缩小文件。</p><p className="my-3 break-words text-sm">上次清理：{date(data.cleanup?.last_success)} · {data.cleanup?.error || '无错误'} · 移除 {data.cleanup?.removed_rows || 0} 行</p><button className={button} disabled={!admin || busy} onClick={() => void act(() => post('storage/cleanup'), '已执行一轮有界清理；大积压会由后台继续处理')}><Database className="mr-1 inline h-4 w-4" />执行有界清理</button></Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(data.tables || []).map((t: RecordData) => <Card key={t.name} title={t.name}><p className="font-mono text-sm">{t.rows == null ? '计数超时' : t.rows.toLocaleString()} 行 · {t.bytes == null ? 'dbstat 不可用' : bytes(t.bytes)}</p></Card>)}</div></>}
      {(section === 'traffic' || section === 'baseline') && <div className="grid gap-4 lg:grid-cols-2">{!items.length && <Empty />}{items.map(i => <Card key={i.entity} title={`${i.host_id} / ${i.name}`}><p className="mb-3 text-xs text-slate-500">{i.runtime} · {i.project || '默认项目'} · {date(i.ts)}</p>{section === 'traffic' ? <><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-slate-400">今日 RX / TX</p><p className="mt-1 font-mono text-sm text-sky-300">{bytes(i.today.rx)} / {bytes(i.today.tx)}</p></div><div><p className="text-xs text-slate-400">本月 RX / TX</p><p className="mt-1 font-mono text-sm text-sky-300">{bytes(i.month.rx)} / {bytes(i.month.tx)}</p></div></div><p className="mt-3 text-xs text-slate-400">覆盖 {Math.round(i.month.covered / 3600 * 10) / 10} 小时 · 间断/重置 {i.month.gaps} · {i.month.estimated ? '含速率估算，不作为精确计费' : '累计计数器差值'}</p>{i.policy.monthly_quota_bytes > 0 && <div className="mt-3"><Status value={(i.month.rx + i.month.tx) >= i.policy.monthly_quota_bytes ? 'critical' : (i.month.rx + i.month.tx) >= i.policy.monthly_quota_bytes * i.policy.quota_warning ? 'warning' : 'healthy'} /><p className="mt-2 text-sm">配额 {bytes(i.policy.monthly_quota_bytes)} · 使用 {Math.round((i.month.rx + i.month.tx) / i.policy.monthly_quota_bytes * 100)}%</p></div>}</> : <><Status value={!i.data.baseline_ready ? 'unavailable' : i.data.anomaly ? 'critical' : 'healthy'} /><p className="mt-3 text-sm text-slate-300">基线入站 {bytes(i.data.medians?.[0])}/s · 连接 {Math.round(i.data.medians?.[1] || 0)}</p><p className="mt-2 text-xs text-slate-400">至少 24 个、跨度一小时的近期样本；流量与连接同时超过 {i.policy.baseline_factor} 倍基线及策略底线，持续三次才告警。不据此自动停业务。</p></>}</Card>)}</div>}
      {section === 'policies' && <><Card title="策略覆盖 / 流量配额"><p className="mb-4 text-xs text-slate-400">主机策略作用于该主机的所有容器；容器覆盖优先。预设是起步值，不是适用于所有业务的统一安全标准。静默只影响运维信号，不解除弱认证/恶意进程防护。</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs text-slate-400">策略身份<select className={`${field} mt-1`} value={selectedEntity} onChange={e => change('entity', e.target.value)}><option value="">请选择节点或容器</option>{overview.hosts.map((h: RecordData) => <option key={h.node} value={JSON.stringify([h.node, 'host', '', '__host__'])}>{h.host_id} / 整个节点</option>)}{(data.entities || []).map((i: RecordData) => <option key={i.entity} value={i.entity}>{i.host_id} / {i.runtime} / {i.name}</option>)}</select></label><label className="text-xs text-slate-400">业务类型<select className={`${field} mt-1`} value={form.profile} onChange={e => change('profile', e.target.value)}>{['general', 'web', 'socks', 'hy2'].map(p => <option key={p}>{p}</option>)}</select></label>{[['quota_gib', '月配额 GiB（0 不限）'], ['connections', '连接警告（可选）'], ['rx_mbps', '入站 Mbps（可选）'], ['http_rps', 'HTTP RPS（可选）'], ['silent_hours', '临时静默小时（0-24）']].map(([k, label]) => <label key={k} className="text-xs text-slate-400">{label}<input type="number" min="0" className={`${field} mt-1`} value={form[k] || ''} onChange={e => change(k, e.target.value)} /></label>)}</div><div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={!admin || busy || !selectedEntity} onClick={() => void act(async () => setPreview(await post('policies/preview', policyPayload())), '预览已生成')}>预览影响</button><button className={button} disabled={!admin || busy || !preview || preview.entity !== selectedEntity} onClick={() => void act(() => post('policies', policyPayload()), '策略已保存')}>保存策略</button></div>{preview && <p className="mt-4 break-words text-sm text-slate-400">连接 {preview.before.connections} → {preview.after.connections}；入站 {bytes(preview.before.rx_bps)}/s → {bytes(preview.after.rx_bps)}/s；{preview.scope}</p>}</Card><div className="grid gap-3 sm:grid-cols-2">{items.map(i => <Card key={i.entity} title={`${i.profile} 策略`}><p className="break-words text-sm">{JSON.parse(i.entity).join(' / ')}</p><p className="mt-2 text-xs text-slate-400">月配额 {bytes(i.data.monthly_quota_bytes)} · 更新时间 {date(i.updated_at)}</p></Card>)}</div></>}
      {section === 'traffic' && <Card title="长期小时 / 日汇总"><div className="mb-4 grid gap-3 sm:grid-cols-3"><label className="text-xs text-slate-400">身份<select className={`${field} mt-1`} value={historyEntity} onChange={e => setHistoryEntity(e.target.value)}><option value="">所有身份（最近最多 2000 桶）</option>{items.map(i => <option key={i.entity} value={i.entity}>{i.host_id} / {i.runtime} / {i.name}</option>)}</select></label><label className="text-xs text-slate-400">汇总粒度<select className={`${field} mt-1`} value={historyPeriod} onChange={e => setHistoryPeriod(e.target.value)}><option value="day">每天</option><option value="hour">每小时（保留 30 天）</option></select></label><label className="text-xs text-slate-400">时间范围<select className={`${field} mt-1`} value={historyDays} onChange={e => setHistoryDays(Number(e.target.value))}>{[7, 31, 180, 400].map(d => <option key={d} value={d}>最近 {d} 天</option>)}</select></label></div>{!(data.buckets || []).length && <Empty text="所选时间范围尚无汇总；部署后开始积累，不补算清理过的历史。" />}<div className="grid gap-3 sm:grid-cols-2">{(data.buckets || []).slice(0, 60).map((r: RecordData) => <div key={`${r.entity}/${r.bucket}`} className="rounded-lg border border-slate-800 p-3"><p className="text-xs text-slate-400">{date(r.bucket)}</p><p className="my-1 break-words text-xs">{JSON.parse(r.entity).join(' / ')}</p><p className="font-mono text-sm text-sky-300">↓ {bytes(r.rx)} · ↑ {bytes(r.tx)}</p><p className="mt-1 text-xs text-slate-400">CPU {r.cpu_avg.toFixed(1)}% · 内存 {r.mem_avg.toFixed(1)}% · 连接峰值 {r.peak_connections}</p><p className="mt-1 text-xs text-slate-500">覆盖 {Math.round(r.covered / 60)} 分钟 · 间断 {r.gaps} · {r.estimated ? '含估算' : '计数器差值'}</p></div>)}</div>{(data.buckets || []).length > 60 && <p className="mt-3 text-xs text-slate-400">显示最近 60 桶；缩短时间范围或选择单个身份查看，完整汇总可通过已认证 API 获取。</p>}</Card>}
      {section === 'incidents' && <><Card title="聚合事件"><p className="mb-4 text-xs text-slate-400">同一节点/运行时/项目/容器内关联异常、处置与恢复。持续样本每五分钟留一次摘要，避免日志无限增长。</p>{!overview.incidents.length && <Empty text="暂无运维事件。" />}{overview.incidents.map((i: RecordData) => <button key={i.id} className="flex w-full flex-wrap items-center justify-between gap-2 border-t border-slate-800 py-3 text-left" onClick={() => void act(async () => setTimeline(await request<RecordData>(`/api/v1/ops/incidents/${i.id}`)), '时间线已打开')}><span className="min-w-0 break-words text-sm">#{i.id} {i.kind} · {JSON.parse(i.entity).join(' / ')}<span className="mt-1 block text-xs text-slate-500">{date(i.opened_at)} → {date(i.last_seen)}</span></span><span className="flex flex-wrap gap-2"><Status value={i.status} />{i.status === 'open' && i.data.severity && <Status value={i.data.severity} />}</span></button>)}</Card>{timeline && <Card title={`事件 #${timeline.incident.id} 时间线`}>{timeline.events.map((e: RecordData) => <div key={e.id} className="border-l-2 border-sky-500/40 py-3 pl-4"><p className="text-xs text-slate-500">{date(e.ts)} · {e.kind}</p><p className="mt-1 break-words text-sm">{e.data.message || e.data.status || e.data.error || JSON.stringify(e.data)}</p></div>)}</Card>}</>}
      {section === 'logs' && <><Card title="HTTP/CC 日志接入向导"><p className="mb-4 text-xs text-slate-400">先在节点发现 nginx/caddy/apache 的日志，再选择可解析文件接入。仅上传格式、方法、状态码统计，不上传原始 URL/IP 或敏感日志内容。容器日志仍由已有容器采集器负责。</p><div className="max-w-lg space-y-3">{hostSelect}<button className={button} disabled={session.role === 'viewer' || busy || !form.host_id} onClick={() => void act(() => post('logs/discover', { host_id: form.host_id }), '发现任务已排队；请等待 Client 执行和新报告')}>发现并预览格式</button></div></Card>{overview.hosts.filter((h: RecordData) => !form.host_id || h.host_id === form.host_id).map((h: RecordData) => <Card key={h.node} title={h.host_id}>{!(h.data.log_discovery || []).length && <Empty text="未发现或尚未执行；确认日志已开启且路径可读。" />}{(h.data.log_discovery || []).map((l: RecordData) => <div key={l.path} className="space-y-2 border-t border-slate-800 py-3"><p className="break-all font-mono text-xs">{l.path}</p><Status value={l.status} /><p className="text-xs text-slate-400">解析 {l.parsed}/{l.samples} · 格式 {l.formats.join(', ') || '未知'} · 方法 {l.methods.join(', ')} · 最近修改 {date(l.modified_at)}</p><button className={button} disabled={!admin || busy || !['healthy', 'idle'].includes(l.status)} onClick={() => setConfirm({ title: '接入访问日志', message: `将 ${h.host_id} 的宿主机日志采集路径设为 ${l.path}；Client 将重启。`, run: () => post('logs/connect', { host_id: h.host_id, paths: [l.path] }) })}>接入此文件</button></div>)}</Card>)}</>}
      {section === 'upgrades' && <><Card title="固定提交灰度升级"><p className="mb-4 text-xs text-slate-400">先升级 Server。以 fork main 固定 SHA 创建发布，所选第一台为灰度，Client 上报目标版本后才可推广。托管发布会暂停节点无条件自动更新定时器，保留上一版以供回滚。</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">已发布的 main 提交 SHA<input className={`${field} mt-1 font-mono`} value={form.revision || ''} onChange={e => change('revision', e.target.value.trim())} /></label><label className="text-xs text-slate-400">目标版本（Server {data.server_version}）<input className={`${field} mt-1`} value={form.version || ''} onChange={e => change('version', e.target.value.trim())} /></label></div><div className="my-4 grid gap-2 sm:grid-cols-2">{(data.nodes || []).map((n: RecordData) => <label key={n.host_id} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" disabled={!admin || busy} checked={(form.hosts || []).includes(n.host_id)} onChange={e => change('hosts', e.target.checked ? [...(form.hosts || []), n.host_id] : form.hosts.filter((x: string) => x !== n.host_id))} /><span className="break-words">{n.host_id} · {n.agent_version} · {date(n.last_seen)}</span></label>)}</div><button className={button} disabled={!admin || busy || !form.hosts?.length} onClick={() => setConfirm({ title: '创建灰度发布', message: `先升级 ${form.hosts[0]}，其余节点等待灰度通过。固定提交 ${form.revision}。`, run: () => post('upgrades', { hosts: form.hosts, revision: form.revision, version: form.version }) })}><GitBranch className="mr-1 inline h-4 w-4" />创建灰度</button></Card>{(data.campaigns || []).map((c: RecordData) => <Card key={c.id} title={`发布 #${c.id} / ${c.version}`}><Status value={c.status} /><p className="my-2 break-all font-mono text-xs text-slate-500">{c.revision}</p>{(data.progress || []).filter((n: RecordData) => n.campaign === c.id).map((n: RecordData) => <div key={n.host_id} className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-800 py-3"><span className="text-sm">{n.host_id} · 上一版 {n.previous_version}</span><Status value={n.status} /></div>)}<button className={button} disabled={!admin || busy || c.status !== 'canary' || !(data.progress || []).some((n: RecordData) => n.campaign === c.id && n.status === 'verified')} onClick={() => setConfirm({ title: '推广灰度版本', message: '将目标固定版本下发给本批次其余节点。', run: () => post(`upgrades/${c.id}/promote`) })}>灰度通过，推广其余节点</button></Card>)}<Card title="回滚到节点保留的上一版">{hostSelect}<button className={`${button} mt-3`} disabled={!admin || busy || !form.host_id} onClick={() => setConfirm({ title: '回滚 Client', message: `恢复 ${form.host_id} 本地保留的上一版 Client 与配置，期间会重启服务。不存在备份时会失败，不会下载未知版本。`, run: () => post('upgrades/rollback', { host_id: form.host_id }) })}>回滚所选节点</button></Card></>}
      {section === 'services' && <><Card title="新增节点侧服务探测"><p className="mb-4 text-xs text-slate-400">HTTP/TCP 由所选 Agent 发起，HTTP 不跟随重定向。TLS 严格验证，提前 14 天提醒过期。存活容器不等于服务正常。</p><div className="grid gap-3 sm:grid-cols-2">{hostSelect}<label className="text-xs text-slate-400">协议<select className={`${field} mt-1`} value={form.kind} onChange={e => change('kind', e.target.value)}><option value="http">HTTP / HTTPS</option><option value="tcp">TCP</option></select></label><label className="text-xs text-slate-400">名称<input className={`${field} mt-1`} value={form.name || ''} onChange={e => change('name', e.target.value)} /></label><label className="text-xs text-slate-400">地址（无凭据）<input className={`${field} mt-1`} placeholder="https://example.com/health 或 tcp://127.0.0.1:443" value={form.target || ''} onChange={e => change('target', e.target.value)} /></label></div><button className={`${button} mt-4`} disabled={!admin || busy || !form.host_id || !form.target} onClick={() => void act(() => post('services', { host_id: form.host_id, name: form.name, target: form.target, kind: form.kind }), '探测已配置；等待节点下次报告')}>添加探测</button></Card><div className="grid gap-4 sm:grid-cols-2">{items.map(i => { const r = (data.results || []).find((x: RecordData) => x.service_id === i.id); const stale = !r || Date.now() / 1000 - r.ts > 900; return <Card key={i.id} title={`${i.host_id} / ${i.name}`}><p className="mb-3 break-all text-xs text-slate-500">{i.data.target}</p><Status value={stale ? 'stale' : r.data.status} /><p className="my-3 text-sm text-slate-400">延迟 {r?.data.latency_ms ?? '—'} ms · HTTP {r?.data.http_status ?? '—'} · TLS 剩余 {r?.data.tls_days_remaining ?? '—'} 天</p><p className="mb-3 text-xs text-rose-300">{r?.data.error}</p><button className={button} disabled={!admin || busy} onClick={() => setConfirm({ title: '移除服务探测', message: `移除 ${i.name} 的探测，不会停止实际服务。`, run: () => request(`/api/v1/ops/services/${i.id}`, { method: 'DELETE' }) })}>移除探测</button></Card>; })}</div></>}
      {section === 'backups' && (admin ? <><Card title="一致性备份"><p className="mb-4 text-xs text-slate-400">SQLite online backup 同时保存数据库内的策略、用户与配置，随后执行完整性检查。备份包含密钥，服务端权限 0600，不提供公网无认证下载。外部 env / TLS 证书请另行离线保管。</p><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-slate-400">间隔（小时）<input type="number" min="1" max="168" className={`${field} mt-1`} value={form.interval_hours} onChange={e => change('interval_hours', Number(e.target.value))} /></label><label className="text-xs text-slate-400">保留份数<input type="number" min="1" max="30" className={`${field} mt-1`} value={form.retention} onChange={e => change('retention', Number(e.target.value))} /></label><button className={button} disabled={busy} onClick={() => void act(() => post('backups/settings', { enabled: true, interval_hours: form.interval_hours, retention: form.retention }), '定时备份已开启')}>启用/更新定时备份</button></div><div className="my-4 flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={() => void act(() => post('backups'), '备份完成并通过 integrity_check')}>立即备份</button><button className={button} disabled={busy} onClick={() => void act(() => post('backups/settings', { enabled: false, interval_hours: form.interval_hours, retention: form.retention }), '定时备份已关闭')}>关闭定时备份</button></div><p className="text-sm text-slate-400">当前 {data.settings?.enabled ? '已启用' : '未启用'} · 最近成功 {date(data.settings?.last_success)} · {data.settings?.error || '无备份错误'}</p></Card><Card title="备份清单 / 恢复说明">{!items.length && <Empty text="尚未创建备份。" />}{items.map(i => <div key={i.name} className="border-t border-slate-800 py-3"><p className="break-all font-mono text-xs">{i.name}</p><p className="mt-1 text-xs text-slate-500">{bytes(i.bytes)} · {date(i.ts)}</p></div>)}<p className="mt-4 text-xs text-slate-400">恢复：先停 Server，备份当前 DB/WAL/SHM 与 env，再对所选备份运行 integrity_check，复制到 monitor.db，清除对应旧 WAL/SHM 后启动并检查健康与登录。详见仓库 docs/operations-runbook.md；此界面不执行在线覆盖。</p></Card></> : <Empty text="仅管理员可管理或查看含密钥备份。" />)}
      {section === 'users' && (admin ? <><Card title="用户与角色"><p className="mb-4 text-xs text-slate-400">admin 管理全部；operator 可诊断/处置；viewer 只读且不能读取通知配置。原有环境管理员保留，数据库不保存明文密码。</p><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-slate-400">用户名<input className={`${field} mt-1`} value={form.username || ''} onChange={e => change('username', e.target.value)} autoComplete="off" /></label><label className="text-xs text-slate-400">密码（至少 12 位）<input type="password" className={`${field} mt-1`} value={form.password || ''} onChange={e => change('password', e.target.value)} autoComplete="new-password" /></label><label className="text-xs text-slate-400">角色<select className={`${field} mt-1`} value={form.role} onChange={e => change('role', e.target.value)}>{['viewer', 'operator', 'admin'].map(r => <option key={r}>{r}</option>)}</select></label></div><button className={`${button} mt-4`} disabled={busy || !form.username || (form.password || '').length < 12} onClick={() => void act(async () => { await post('users', { username: form.username, password: form.password, role: form.role }); change('password', ''); }, '用户已保存') }><Users className="mr-1 inline h-4 w-4" />创建 / 更新账号</button><p className="mt-4 text-xs text-slate-500">环境管理员：{data.environment_admin}</p>{items.map(i => <div key={i.username} className="mt-3 flex flex-wrap items-center justify-between gap-2"><span>{i.username} / {i.role}</span><button className={button} disabled={busy || i.username === session.username} onClick={() => setConfirm({ title: '删除账号', message: `撤销 ${i.username} 的面板访问权限。`, run: () => request(`/api/v1/ops/users/${encodeURIComponent(i.username)}`, { method: 'DELETE' }) })}>撤销</button></div>)}</Card><Card title="变更审计（最近 100 条）">{(data.audit || []).map((a: RecordData) => <div key={a.id} className="border-t border-slate-800 py-3"><p className="break-words text-sm">{a.username} · {a.method} {a.path} · HTTP {a.status}</p><p className="mt-1 text-xs text-slate-500">{date(a.ts)}</p></div>)}</Card></> : <Empty text="仅管理员可管理用户和审计记录。" />)}
    </>}
    <div className="flex flex-wrap items-center gap-2 border-t border-slate-800 pt-4 text-xs text-slate-500"><Shield className="h-4 w-4" /><span>管理 API 均经过认证与角色校验；数据时间为北京时间。</span><CheckCircle2 className="h-4 w-4 text-emerald-400" /><span>正常</span><AlertTriangle className="h-4 w-4 text-amber-400" /><span>警告</span><FileText className="h-4 w-4 text-rose-400" /><span>危险</span></div>
    <ConfirmDialog open={!!confirm} title={confirm?.title || ''} description={confirm?.message || ''} confirmLabel={busy ? '正在执行…' : '确认执行'} onConfirm={() => { if (confirm) void act(confirm.run); }} onCancel={() => { if (!busy) setConfirm(null); }} isSubmitting={busy} />
  </div>;
}
